# Ejercicios Numpy I

Sirvan estos ejercicios para que fortalezcáis aquellos conceptos más importantes.

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
import numpy as np
print(np.version.version)


1.20.2


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [2]:
my_array = np.arange(0,10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [3]:
true = [[True, True, True], [True, True, True], [True, True, True]]
arr_true = np.array(true)
arr_true

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [4]:
impares = my_array[my_array % 2 != 0]
impares


array([1, 3, 5, 7, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [5]:
my_array[my_array % 2 != 0] = -1
my_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [6]:
new_arr = np.where(my_array % 2 == 0, my_array, -1 )
new_arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [7]:
my_array.reshape(2, 5)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [8]:
b = np.repeat(1, 10).reshape(2,-1)
a = np.arange(10).reshape(2,-1)
np.concatenate((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [9]:
b = np.repeat(1, 10).reshape(2,-1)
a = np.arange(10).reshape(2,-1)
np.hstack((a,b) )

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [10]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)


array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [11]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [12]:
my_array = np.arange(0,10)
arr_2 = my_array * 10
print(my_array[1:8])


[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [18]:
my_matrix = np.array([[1, 2, 3],[5, 6, 7],[9, 10, 11]])
my_matrix

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [21]:
sec = np.arange(1, 50, 3)
sec

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [25]:
sec2 = np.arange(4, 1., -0.25)
sec2

array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ,
       1.25])

## Ejercicio 16
Lee la imagen `numpy.png` que encontrarás en la carpeta **img**

In [29]:
from skimage.io import imread
imagen = imread("./theory/numpy/img/numpy.png")
print(imagen)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 ...

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [34]:
arr_4x1 = np.array([[1], [2], [3], [4]])
arr_2x2 = arr_4x1.reshape(2,2)
print(arr_2x2)


[[1 2]
 [3 4]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [41]:
y = np.random.randint(1, 100, size = (4, 5, 3))
y

array([[[53, 39, 72],
        [ 5, 47, 85],
        [ 4, 68,  3],
        [16, 11, 36],
        [44,  3,  9]],

       [[17, 72, 59],
        [27, 98,  5],
        [52, 27, 32],
        [96, 20, 95],
        [81, 68, 57]],

       [[38, 81,  3],
        [98, 83, 19],
        [ 5, 20,  9],
        [93, 61, 77],
        [43, 25, 74]],

       [[93, 85, 83],
        [50, 92, 52],
        [12, 78, 76],
        [78, 24, 44],
        [76, 80, 33]]])

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [40]:
z = np.array([[True], [True], [True], [True], [True], [True], [True], [True], [True], [True]])
z.reshape(2,5)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [36]:
x =np.random.randint(10, 20, size = (5,2,6))
# 1. 6 elementos
# 2. 3 dimensiones
# 3. 5 elementos

array([[[17, 18, 13, 10, 11, 19],
        [14, 12, 14, 16, 19, 13]],

       [[16, 11, 19, 19, 11, 13],
        [14, 16, 18, 17, 19, 17]],

       [[19, 19, 16, 16, 14, 11],
        [10, 14, 10, 18, 19, 15]],

       [[15, 10, 10, 17, 13, 14],
        [10, 12, 18, 10, 16, 18]],

       [[16, 18, 13, 15, 11, 17],
        [14, 19, 10, 11, 17, 14]]])

In [42]:
import sys
print(sys.path)

['c:\\Users\\jarai\\Desktop\\Python_work\\TheBridge\\Javier_Araiz_TheBridge\\week4_EDA_np_pd_json_apis_regex\\day1_numpy_pandas_I',
 'c:\\Users\\jarai\\.vscode\\extensions\\ms-toolsai.jupyter-2021.5.745244803\\pythonFiles',
 'c:\\Users\\jarai\\.vscode\\extensions\\ms-toolsai.jupyter-2021.5.745244803\\pythonFiles',
 'c:\\Users\\jarai\\.vscode\\extensions\\ms-toolsai.jupyter-2021.5.745244803\\pythonFiles\\lib\\python',
 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\\python38.zip',
 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\\DLLs',
 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\\lib',
 'C:\\Users\\jarai\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0',
 '',
 'C:\\Users\\jarai\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python