# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [11]:
import numpy as np
my_array = np.arange(0,10)
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [21]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [22]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [33]:
matrix = np.arange(1,21).reshape((4,5))
print(matrix)
matrix.T

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [32]:
sliced = matrix[:2, :2]
sliced

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [84]:
rows = np.array([0, 2], dtype = np.intp)
columns = np.array([0, 2, 4], dtype = np.intp)
rows[:, np.newaxis]
matrix[rows[:, np.newaxis], columns]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [90]:
np.flip(matrix.reshape((4, 5))[0:3][::-1])



array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [96]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
y = np.where(x == "Loro", True, False)
filtered = x[y]
filtered

array(['Loro', 'Loro'], dtype='<U5')

In [99]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
z = []
for elem in x:
    if elem == "Loro":
        z.append(True)
    else:
        z.append(False)
filtered2 = x[z]
filtered2   

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [102]:
seq = np.arange(1, 21).reshape(2, 5, 2)
seq

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [106]:
np.flip(matrix)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [112]:
os = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
os[3] = 1
os

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [115]:
vectr = np.arange(10, 50)
vectr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [139]:
new_matrix = np.random.rand(10,10)
print(np.amax(new_matrix))
print(np.amin(new_matrix))
new_matrix

0.9626400746741732
0.006659067924726814


array([[0.05905702, 0.25152686, 0.37686021, 0.31408448, 0.89793397,
        0.65685639, 0.3403013 , 0.61559088, 0.79576893, 0.33808566],
       [0.38304841, 0.41541565, 0.72054636, 0.34369669, 0.1831488 ,
        0.28540684, 0.80568632, 0.24360356, 0.85071701, 0.58663137],
       [0.10827306, 0.38693429, 0.11553752, 0.78453917, 0.83666065,
        0.0749537 , 0.26495217, 0.52113673, 0.83554631, 0.22203028],
       [0.9027312 , 0.96264007, 0.40851363, 0.51708702, 0.66965205,
        0.30987742, 0.89838966, 0.28389334, 0.54888271, 0.78633655],
       [0.07672548, 0.07323343, 0.20376405, 0.63287069, 0.12052042,
        0.90143024, 0.2299403 , 0.06183469, 0.42035947, 0.72112089],
       [0.44740644, 0.89041582, 0.54703975, 0.04733917, 0.24496495,
        0.17795173, 0.94548049, 0.43136481, 0.44955535, 0.30800424],
       [0.29942298, 0.1573931 , 0.34356526, 0.1680438 , 0.57753074,
        0.66558132, 0.65222306, 0.36616841, 0.48788203, 0.82911266],
       [0.40906784, 0.48296466, 0.9550059

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [138]:
vctr1 = np.random.rand(30)
print(vctr1)
np.mean(vctr1)

[0.80422074 0.53784482 0.62831403 0.95461284 0.56175106 0.53535986
 0.59512925 0.98758533 0.07258946 0.6903535  0.61424936 0.05030715
 0.40018564 0.50287308 0.09334068 0.59176841 0.38882863 0.45448636
 0.40130058 0.24874951 0.52440664 0.54804019 0.62159956 0.18180447
 0.98806182 0.65188599 0.43303122 0.58631972 0.9610617  0.29706462]


0.5302375410582554

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [163]:
cuadrado = np.arange(1,101).reshape(10,10)
cuadrado[:] = 0
cuadrado[:1] = 1
cuadrado[:, :1] = 1
cuadrado[-1:] = 1
cuadrado[:, -1] = 1
cuadrado


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [240]:
matriz = np.zeros((8,8), dtype= int)
matriz[::2, 1::2] = 1
matriz[1::2, ::2] = 1
print(matriz[0])
print(np.where(matriz[0] == 1, matriz, True) == True)
matriz

[0 1 0 1 0 1 0 1]
[[ True  True  True  True  True  True  True  True]
 [ True False  True False  True False  True False]
 [ True  True  True  True  True  True  True  True]
 [ True False  True False  True False  True False]
 [ True  True  True  True  True  True  True  True]
 [ True False  True False  True False  True False]
 [ True  True  True  True  True  True  True  True]
 [ True False  True False  True False  True False]]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [187]:
chess = np.array([0, 1])
np.tile(chess,(8,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [233]:
mat = np.random.rand(5,5)
res = (mat - np.mean(mat)) / np.std(mat)
print(res)

[[-1.0347369   1.60828747  0.82518266 -0.63934338 -0.32723244]
 [-1.42981126  1.27511096  0.76131156 -0.21100291 -1.40250082]
 [-0.62709946  0.49841458  0.16369389 -0.44400213 -0.35286057]
 [ 1.332405    0.72457086 -1.74103193 -0.67442676  1.96438167]
 [ 0.12694783  0.35419431  0.0394165   0.78706391 -1.57693264]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [203]:
arr = np.arange(0, 11)
arr[3:9] = -1
print(arr)
new_arr = np.where(arr != -1)
print(new_arr)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
(array([ 0,  1,  2,  9, 10], dtype=int64),)


## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [241]:
tablero = np.array(["( )","( )","( )","( )","( )","( )","( )","( )","( )","( )"] * 10).reshape(10,10)
tablero[0,1]= "(O)"
tablero[1,1] = "(O)"
tablero[5, 0:4] = "(O)"
tablero[5, 0] = "(X)"
tablero[2, 8] = "(-)"
print(tablero)

[['( )' '(O)' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )']
 ['( )' '(O)' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )']
 ['( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '(-)' '( )']
 ['( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )']
 ['( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )']
 ['(X)' '(O)' '(O)' '(O)' '( )' '( )' '( )' '( )' '( )' '( )']
 ['( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )']
 ['( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )']
 ['( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )']
 ['( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )' '( )']]


In [254]:
import random
orientacion = "NSEO"
contador = 1
while contador > 0:
    coordenada = random.choice(orientacion)
    x = random.randint(1,9)
    y = random.randint(1,9)
    try:
        if tablero[x,y] != "(O)":
            tablero[x,y] = "(O)"
            if coordenada == "N":
                try:
                    if np.where(tablero[y] != "(O)", x, True) == True:
                        tablero[x:[x - 3]] = "(O)"
                        contador -= 1
                    else:
                        continue
                except:
                    continue
            if coordenada == "S":
                try:
                    if np.where(tablero[y] != "(O)", x, True) == True:
                        tablero[x:[x + 3]] = "(O)"
                        contador -= 1
                    else:
                        continue
                except:
                    continue
            if coordenada == "E":
                try:
                    if np.where(tablero[x] != "(O)", x, True) == True:
                        tablero[y:[y + 3]] = "(O)"
                        contador -= 1
                    else:
                        continue
                except:
                    continue
            if coordenada == "O":
                try:
                    if np.where(tablero[x] != "(O)", x, True) == True:
                        tablero[y:[y + 3]] = "(O)"
                        contador -= 1
                    else:
                        continue
                except:
                    continue
    except:
        continue
            
print(tablero)

KeyboardInterrupt: 

In [255]:
import sys
print(sys.path)

['c:\\Users\\jarai\\Desktop\\Python_work\\TheBridge\\Javier_Araiz_TheBridge\\week4_EDA_np_pd_json_apis_regex\\day1_numpy_pandas_I', 'c:\\Users\\jarai\\.vscode\\extensions\\ms-toolsai.jupyter-2021.5.745244803\\pythonFiles', 'c:\\Users\\jarai\\.vscode\\extensions\\ms-toolsai.jupyter-2021.5.745244803\\pythonFiles', 'c:\\Users\\jarai\\.vscode\\extensions\\ms-toolsai.jupyter-2021.5.745244803\\pythonFiles\\lib\\python', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\\python38.zip', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\\DLLs', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\\lib', 'C:\\Users\\jarai\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0', '', 'C:\\Users\\jarai\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-